sudo: true
language: generic


cache:
  directories:
    - $HOME/.cache/latex

addons:
  apt:
    packages:
      - texlive
      - wget
      - curl
      - sed
      - grep


matrix:
  include:
    - os: linux
      name: ubuntu 14.04
      addons:
         apt:
           packages:
             - latexmk
             - texlive
             - wget
             - curl
             - sed
             - grep

  timeout: 3600


install:
  - test -z "$LATEXMK" || which latexmk
  - mkdir -p "$HOME"/.cache/latex
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/comment/comment.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/misc/nextpage.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/fonts/stmaryrd.zip
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/wallpaper/wallpaper.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/generic/xstring/xstring.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/generic/xstring/xstring.tex
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/enumitem/enumitem.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/mathtools.zip
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/generic/diagrams/xypic.zip
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/etoolbox/etoolbox.def
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/etoolbox/etoolbox.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/titlesec.zip
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/braket/braket.sty
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/supertabular/supertabular.dtx http://mirrors.ctan.org/macros/latex/contrib/supertabular/supertabular.ins
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/soul/soul.dtx http://mirrors.ctan.org/macros/latex/contrib/soul/soul.ins
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/macros/latex/contrib/xcolor/xcolor.dtx http://mirrors.ctan.org/macros/latex/contrib/xcolor/xcolor.ins
  - ./etc/ci/wget_retry.sh http://mirrors.ctan.org/graphics/pgf/base.zip
  - cp "$HOME"/.cache/latex/* ./
  - unzip stmaryrd && mv stmaryrd/*.{mf,dtx} ./ && latex stmaryrd.dtx
  - unzip mathtools.zip && (cd mathtools && for i in *.dtx; do (mv $i ../ && cd .. && tex $i); done)
  - unzip xypic.zip && mv xypic/*/* ./
  - unzip titlesec.zip && mv titlesec/*.{tss,sty,def} ./
  - latex supertabular.ins
  - latex soul.ins
  - latex xcolor.ins
  - unzip base && find base -name "*.sty" -o -name "*.tex" -o -name "*.def" -o -name "*.cfg" | grep -v pgfmanual | xargs cp -t ./

script:

  - make thesis
