sudo: true
language: generic


matrix:
  include:
    - os: linux

  cache:
    directories:
      - "/tmp/texlive"
      - "$HOME/.texlive"

  timeout: 3600


before_install:
  - chmod 777 ./utility/travis_setup.sh
  - travis_wait 45 bash ./utility/travis_setup.sh
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
  - sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get update && sudo apt-get install -y inkscape && inkscape --version

script:

  - make
