site_name:          PhDThesis
repo_url:           https://github.com/Nico-Curti/PhDthesis
site_description:   PhD Thesis in applied physics
site_author:        https://www.unibo.it/sitoweb/nico.curti2

extra_css:          assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Nico-Curti'
    - type: 'Unibo'
      link: 'https://www.unibo.it/sitoweb/nico.curti2'


markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys

  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - md/Abstract.md
  - md/READMEduction.md
  - md/Chapter1/README.md
  - md/Chapter1/DNetPRO/README.md
  - md/Chapter1/DNetPRO/ToyModel.md
  - md/Chapter1/Implementation/README.md
  - md/Chapter1/Implementation/Couples.md
  - md/Chapter1/Implementation/Sorting.md
  - md/Chapter1/Implementation/FeatSel.md
  - md/Chapter1/Implementation/Python.md
  - md/Chapter1/Implementation/Pipeline.md

  - md/Chapter2/README.md
  - md/Chapter2/NeuralNetwork/README.md

  - md/Chapter3/README.md

  - md/Appendix/BlendNet/README.md
  - md/Appendix/DiscriminantAnalysis/README.md

  - md/Conclusions.md
  - authors.md

theme:              jekyll-theme-slate

#   feature:
#     tabs: true

#   language: 'en'

#   extra:
#     search:
#       language: 'en'
#       tokenizer: '[\s\-\.]+'

# nav:
#   - About Me: authors.md

#   - READMEduction:
#     - Abstract: md/Abstract.md
#     - READMEduction: md/READMEduction.md

#   - Feature Selection:
#       - READMEduction: md/Chapter1/README.md

#   - Neural Network:
#       - READMEduction: md/Chapter2/README.md

#   - CHIMeRA:
#       - READMEduction: md/Chapter3/README.md

#   - BlendNet:
#       - READMEduction: md/Appendix/BlendNet/README.md

#   - Conclusions:
#       - Conclusions: md/Conclusions.md


