site_name:          PhDThesis
repo_url:           https://github.com/Nico-Curti/PhDthesis
site_description:   PhD Thesis in applied physics
site_author:        https://www.unibo.it/sitoweb/nico.curti2

extra_css:          assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - md/Abstract.md
  - md/Introduction.md
  - md/Chapter1/Intro.md
  - md/Chapter1/DNetPRO/Intro.md
  - md/Chapter1/DNetPRO/ToyModel.md
  - md/Chapter1/Implementation/Intro.md
  - md/Chapter1/Implementation/Couples.md
  - md/Chapter1/Implementation/Sorting.md
  - md/Chapter1/Implementation/FeatSel.md
  - md/Chapter1/Implementation/Python.md
  - md/Chapter1/Implementation/Pipeline.md

  - md/Chapter2/Intro.md
  - md/Chapter2/NeuralNetwork/Intro.md

  - md/Chapter3/Intro.md

  - md/Appendix/BlendNet/Intro.md
  - md/Appendix/DiscriminantAnalysis/Intro.md

  - md/Conclusions.md
  - authors.md

theme:              jekyll-theme-slate
