site_name:          PhDThesis
repo_url:           https://github.com/Nico-Curti/PhDthesis
site_description:   PhD Thesis in applied physics
site_author:        https://www.unibo.it/sitoweb/nico.curti2

extra_css:          assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Nico-Curti'
    - type: 'Unibo'
      link: 'https://www.unibo.it/sitoweb/nico.curti2'


markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys

  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - md/Abstract.md
  - md/Introduction.md
  - md/Chapter1/Intro.md
  - md/Chapter1/DNetPRO/Intro.md
  - md/Chapter1/DNetPRO/ToyModel.md
  - md/Chapter1/Implementation/Intro.md
  - md/Chapter1/Implementation/Couples.md
  - md/Chapter1/Implementation/Sorting.md
  - md/Chapter1/Implementation/FeatSel.md
  - md/Chapter1/Implementation/Python.md
  - md/Chapter1/Implementation/Pipeline.md

  - md/Chapter2/Intro.md
  - md/Chapter2/NeuralNetwork/Intro.md

  - md/Chapter3/Intro.md

  - md/Appendix/BlendNet/Intro.md
  - md/Appendix/DiscriminantAnalysis/Intro.md

  - md/Conclusions.md
  - authors.md

theme:              jekyll-theme-slate

  feature:
    tabs: true

  language: 'en'

  extra:
    search:
      language: 'en'
      tokenizer: '[\s\-\.]+'

nav:
  - About Me: authors.md

  - Introduction:
    - Abstract: md/Abstract.md
    - Introduction: md/Introduction.md

  - Feature Selection:
      - Introduction: md/Chapter1/Intro.md

  - Neural Network:
      - Introduction: md/Chapter2/Intro.md

  - CHIMeRA:
      - Introduction: md/Chapter3/Intro.md

  - BlendNet:
      - Introduction: md/Appendix/BlendNet/Intro.md

  - Conclusions:
      - Conclusions: md/Conclusions.md


